pool:
  vmImage: 'ubuntu-latest'
trigger:
- main
variables:
  AWS_ACCESS_KEY_ID:  $(AWS_ACCESS_KEY_ID)
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

  
stages:
  - stage: Deploy
    jobs:
      - job: TerraformJob
        steps:
          - bash: |
              terraform init
            displayName: 'Terraform Init'
          - bash: |
              terraform plan 
            displayName: 'Terraform Plan'
          - bash: |
              terraform apply -auto-approve
            displayName: 'Terraform Apply'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
